--- 
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: javawebapp
spec: 
  selector: 
    matchLabels: 
      app: javawebapp 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: javawebapp 
    spec: 
      containers: 
      - name: javawebapp
        image:  agunuworld/java-web-app:22
        ports: 
        - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: javawebapp
  name: javawebapp
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: javawebapp
