apiVersion: apps/v1
kind: Deployment
metadata:
  name: mss-prod-pod
  namespace: mss-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: java-app
      labels:
        app: java-app
    spec:
      # imagePullSecrets:
      #   - name: regcred
      # affinity:
      #   nodeAffinity:
          ##kubectl label node mss-node02 mss-node02=ssd
          # requiredDuringSchedulingIgnoredDuringExecution:
          #   nodeSelectorTerms:
          #   - matchExpressions:
          #     - key: mss-node02
          #       operator: In
          #       values:
          #       - ssd
      containers:
      - name: mss-prod-con
        image: replace
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
             cpu: 100m
             memory: 512Mi
        readinessProbe:
          httpGet:
            path: /healthz-app
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /healthz-app
            port: 8080
          initialDelaySeconds: 200
          timeoutSeconds: 15
          periodSeconds: 15
